//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "144.0.26+g8b05ce5+chromium-144.0.7559.252"
#define CEF_VERSION_MAJOR 144
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 26
#define CEF_COMMIT_NUMBER 3427
#define CEF_COMMIT_HASH "8b05ce5f25dbea1921896d2b2008cbc1dc90b636"
// clang-format on

#endif // CefVersion
